---
apiVersion: "config.istio.io/v1alpha2"
kind: attributemanifest
metadata:
  name: istio-proxy
  namespace: default
spec:
  attributes:
    source.uid:
      value_type: STRING
    source.groups:
      value_type: STRING
    destination.namespace:
      value_type: STRING
    destination.service:
      value_type: STRING
    request.method:
      value_type: STRING
    request.path:
      value_type: STRING
    source.service:
      value_type: STRING
    destination.service:
      value_type: STRING
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: jwtauthorization
  namespace: istio-system
spec:
  match: destination.labels["app"] == "hp-company"
  actions:
  - handler: jwthandler.opa
    instances:
    - jwtauthzinstance.authorization
---
apiVersion: "config.istio.io/v1alpha2"
kind: authorization
metadata:
  name: jwtauthzinstance
  namespace: istio-system
spec:
  subject:
    user: source.uid | ""
  action:
    namespace: destination.namespace | "default"
    service: destination.service | ""
    method: request.method | ""
    path: request.path | ""
    properties:
      token: request.headers["authorization"] | ""
---
apiVersion: "config.istio.io/v1alpha2"
kind: opa
metadata:
  name: jwthandler
  namespace: istio-system
spec:
  policy:
    - |+
      package mixerauthz
      # Deny request by default.
      default allow = false
      allow{
            not_blacked
       }
      not_blacked {
        blackItem := {signature | signature := blacklist[_]; signature ==input.action.properties.token}
        count(blackItem) == 0
        }
      blacklist[signatures] {
         response:=http.send({"method": "get", "url": "hp-oauth-service.hp/oauth/api/v1/blacklist/access"})
         signatures=response.blacklist[_].signature
       }
  checkMethod: "data.mixerauthz.allow"
  failClose: true
---
